---
  language: go
  sudo: false
  notifications:
    email: true
  go:
    - 1.x
    - tip
  matrix:
    allow_failures:
      - go: tip
    fast_finish: true
  install:
    - go get github.com/golang/lint/golint
    - go get honnef.co/go/tools/cmd/staticcheck
  script:
    - make all
    - make cover
    - make release
  after_success:
    - bash <(curl -s https://codecov.io/bash)
  deploy:
    provider: releases
    api_key:
      secure: "R1ABRhNyFqEvVzMWzsEwgt104p5M4ofpTyUraXZgAj8sEGAZrVedJz42bbC3rtdVxBEvfWiXGR1DYV5F+sEuhYyD7DQhezi4aTSK0zEepdf96P7fqkN/ssUAMql2WhKoJPpBmAovZwrT+77ZkUPRKSYWXTgFOIT7u2RtaV9dI2s6SQXgL0ebySLQM/4UFvAwZxCGg19VhgR3ehDCl+SLIP/0keaRsKVXdakHS3nCiN3efCOKqNiVpQd+NtpTGU+OCdfAxObaeJmgL1Uowl/mRJ6bKLzBh4d5K0f53Dpo1dxnhk7UbE+MIpgyazzahLV/wXSTpXix17sTAYCF6rTwpVn8W/XYN1PAC2KJHRkVtpu1Mioj6RwoQQKqYhZKBZ6ACZOISIe9dTjlTnay7BGiM4TadfZvUVRBr2BhoJKz69Z7CIjl09Kd4K9OnXea/BoqdG1s3VSXWxVRrytFWe10MiTrF8YIlWNzo3Edm14xVrguG5nFy8vafldfBI+rDdVMhJKzTJ/PqJk16IduJFu4PpyWayc5Qt0nPNaeVO4kVo7UmacUHuAEI9QHViRSvAuSrVq21XZ0uNxTM81K5Heh5FEBPXzVk93ORWGNzFe3l+vI8a/QS9dkvD0Jv2w40MpK4lUyRBPg7ZaR7cUHqvASjGjGyuh5PZkFZxgWGg9haPI="
    file:
      - cross/magneto-linux-amd64.md5
      - cross/magneto-linux-arm
      - cross/magneto-linux-arm64.sha256
      - cross/magneto-linux-arm.sha256
      - cross/magneto-linux-386.sha256
      - cross/magneto-linux-arm64.md5
      - cross/magneto-linux-arm64
      - cross/magneto-linux-amd64.sha256
      - cross/magneto-linux-386.md5
      - cross/magneto-linux-arm.md5
      - cross/magneto-linux-386
      - cross/magneto-linux-amd64
    skip_cleanup: true
    on:
      tags: true
